name: hello workflow

on:
  push: 
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Using pre actions
        uses: actions/checkout@v4

      - name: Greeting to a user 
        run: echo "Hello from GitHub Actions!"


      
