name: hello workflow

on:
  push: 
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps: 
      - name: Using pre actions
        uses: actions/checkout@v4

      - name: Greeting to a user 
        run: echo "Hello from GitHub Actions!"

  current_details:
    runs-on: ubuntu-latest
    steps:
      - name: Current date & time detail
        run : echo 'date'

      - name: Branch name
        run: echo '${{ github.ref_name }}'

      - name: list the files in repo
        run: ls -la

      - name: runner operating system
        run: echo "cat /etc/os-release"
        
