name: Install-python-versions

on:
  push:
    branches: [main]

jobs:
  py-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Install python
        run: |
          echo ${{ matrix.os }}
          sudo apt install -y python${{ matrix.python-version }}
          python -v

    
