name: Install-python-versions

on:
  push:
    branches: [main]

jobs:
  py-version:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        include:
          - inputs:
            - true 
            
              
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Install python
        run: |
          sudo apt install -y python3
          python -v

    
