name: task3
on:
  push:
    branches: [main]
jobs:
  op:
    runs-on: ubuntu_latest
    steps:
      - name: a job that sets an output
        id: my_date
        run: echo "date=$date" >> $GITHUB_OUTPUT
  prntop:
    runs-on: ubuntu_latest
    steps:
      - name: Read previous job & print it
        run: echo "$steps.my_date.outputs.date"


